// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXWPFAppWithDocFxLoggingAndZip
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXWPFAppWithDocFxLoggingAndZip.71165e23-89de-466e-8e29-f204763578ab";
        public const string Name = "VSIXWPFAppWithDocFxLoggingAndZip";
        public const string Description = @"WPF Application .Net 6 With DocFx, Logging And Zip support under Visual Studio 2022. 
Updated Project Capabilities to include 'Microsoft.Extensions.Logging, DocFx.Console, and System.IO.Compression'";
        public const string Language = "en-US";
        public const string Version = "17.1";
        public const string Author = "Danny McNaught";
        public const string Tags = "WPF; CSharp";
    }
}
