// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VSIXWPFAppWithDocFxLoggingAndZip
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSIXWPFAppWithDocFxLoggingAndZipString = "2bd87c78-761b-4ca5-a2af-34f86a0c3c27";
        public static Guid VSIXWPFAppWithDocFxLoggingAndZip = new Guid(VSIXWPFAppWithDocFxLoggingAndZipString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}